// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4lcY_x2AD7Zzcg7jOXEmIYjYVp8uIGUs',
    appId: '1:510702297546:web:35adea88ca72251ff52f33',
    messagingSenderId: '510702297546',
    projectId: 'deliveryapp-93130',
    authDomain: 'deliveryapp-93130.firebaseapp.com',
    storageBucket: 'deliveryapp-93130.appspot.com',
    measurementId: 'G-3DW5T706ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wuvEs85ju-EnZcUtiVf6Zl13Ydgr8qw',
    appId: '1:510702297546:android:83fd32066a6d18fbf52f33',
    messagingSenderId: '510702297546',
    projectId: 'deliveryapp-93130',
    storageBucket: 'deliveryapp-93130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvM4YmE0q_xSQyaPA5P24i9Pku_tpYGYA',
    appId: '1:510702297546:ios:2918a8216e0516daf52f33',
    messagingSenderId: '510702297546',
    projectId: 'deliveryapp-93130',
    storageBucket: 'deliveryapp-93130.appspot.com',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvM4YmE0q_xSQyaPA5P24i9Pku_tpYGYA',
    appId: '1:510702297546:ios:23bf68f9dc848ac4f52f33',
    messagingSenderId: '510702297546',
    projectId: 'deliveryapp-93130',
    storageBucket: 'deliveryapp-93130.appspot.com',
    iosBundleId: 'com.example.deliveryapp.RunnerTests',
  );
}
